local S = minetest.get_translator("basic_ground_nodes")

--for easier movability. Moving this may mess up existing worlds
local modname = minetest.get_current_modname()


--stone, rubble and corresponding ores
rocks_api.register_rock(modname .. ":stone", "Stone",
	modname .. "_stone.png", modname .. "_rubble.png", "basic_ground_nodes")
minetest.register_alias("mapgen_stone", modname .. ":stone")
minetest.register_alias("stone", modname .. ":stone")



--dirt
minetest.register_node(modname .. ":dirt",
{
	description = S("Dirt"),
	tiles = {modname .. "_dirt.png"},
	groups = {crumbly = 2, soil = 1},
	sounds = generic_media.node_sound_dirt_defaults(),
	drop = "",

})
minetest.register_alias("dirt", modname .. ":dirt")


--scorched dirt
minetest.register_node(modname .. ":dirt_scorched",{
	description = S("Scorched Dirt"),
	tiles = {modname .. "_dirt_scorched.png"},
	groups = {crumbly = 2, soil = 1},
	sounds = generic_media.node_sound_dirt_defaults(),
	drop = "",
})
minetest.register_alias("scorched_dirt", modname .. ":dirt_scorched")

erosion.register_erosion(
{
	modname .. ":dirt",
	modname .. ":dirt_scorched"
})


--sand
minetest.register_node(modname .. ":sand",{
	description = S("Sand"),
	tiles = {modname .. "_sand.png"},
	groups = {crumbly = 2},
	sounds = generic_media.node_sound_sand_defaults(),
	drop = "",
})
minetest.register_alias("sand", modname .. ":sand")
erosion.register_erosion(
{
	modname .. ":sand"
})
